config/routes.rb
UserMaintenance::Engine.routes.draw do

  devise_for :users, class_name: "UserMaintenance::User", :module => :devise

  resource :user, :as => :profile, :path => :profile, :only => [:show, :edit, :update] do
    get 'edit_password'
    patch 'update_password'
  end

  scope '/admin', :except => :destroy do
    resources :users do
      member do
        get 'reset_password' => 'users#resetting_password'
        patch 'reset_password' => 'users#reset_password'
        patch 'enable'
      end
    end
  end

end

app/models/user_maintenance/user.rb
module UserMaintenance
  class User < ActiveRecord::Base
    include RoleModel

    devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

    roles_attribute :role
    roles :admin, :user

    belongs_to :password_last_updated_by, :class => UserMaintenance::User, :foreign_key => :password_last_updated_by_user_id

    validates :role, :first_name, :last_name, :presence => true
    validate :only_one_role_assigned

    def self.valid_roles_map
      valid_roles.map do |role|
        [role.to_s.titleize, self.mask_for(role)]
      end
    end

    def active_for_authentication?
      super && self.enabled?
    end

    def full_name
      "#{first_name} #{last_name}"
    end

    private

    def only_one_role_assigned
      errors.add(:role, :equal_to) if role && !power_of_two?(role)
    end

    def power_of_two?(number)
      number & (number - 1) == 0
    end

  end
end

app/controllers/user_maintenance/application_controller.rb
module UserMaintenance
  class ApplicationController < ActionController::Base
    protect_from_forgery :with => :exception

    check_authorization :unless => :devise_controller?

    rescue_from CanCan::AccessDenied do |exception|
      redirect_to main_app.root_url, :alert => exception.message
    end

    private

    def after_sign_in_path_for(resource)
      if resource != resource.password_last_updated_by
        edit_password_profile_path
      else
        request.env['omniauth.origin'] || stored_location_for(resource) || main_app.root_path
      end
    end

    def permitted_params
      @permitted_params = PermittedParams.new(params)
    end

    helper_method :permitted_params
  end
end

app/controllers/user_maintenance/users_controller.rb
require_dependency "user_maintenance/application_controller"

module UserMaintenance
  class UsersController < ApplicationController
    load_and_authorize_resource

    def index
      @users = UserMaintenance::User.where.not(:id => current_user.id)
    end

    def show
      @user ||= current_user
    end

    def new
    end

    def create
      @user.password_last_updated_by = current_user

      if @user.save
        redirect_to @user
      else
        render 'new'
      end
    end

    def edit
      @user ||= current_user
    end

    def update
      @user ||= current_user

      if @user.update_attributes(update_params)
        redirect_to((can? :update_profile, @user) ? profile_path : user_path(@user))
      else
        render 'edit'
      end
    end

    def enable
      if @user.update(:enabled => !@user.enabled)
        redirect_to users_path
      else
        render 'show'
      end
    end

    def edit_password
    end

    def update_password
      current_user.password_last_updated_by = current_user

      if current_user.update_with_password(update_password_params)
        sign_in current_user, :bypass => true
        redirect_to profile_path
      else
        render 'edit_password'
      end
    end

    def resetting_password
    end

    def reset_password
      @user.password_last_updated_by = current_user

      if @user.update_attributes(reset_password_params)
        redirect_to @user
      else
        render 'resetting_password'
      end
    end

    private

    def create_params
      params.require(:user).permit(*user_attributes)
    end

    def update_params
      updatable_fields = (user_attributes - [:password, :password_confirmation])

      params.require(:user).permit(*updatable_fields)
    end

    def user_attributes
      [
        :last_name,
        :first_name,
        :email,
        :password,
        :password_confirmation,
        :role
      ]
    end

    def update_password_params
      params.require(:user).permit(:current_password, :password, :password_confirmation)
    end

    def reset_password_params
      params.require(:user).permit(:password, :password_confirmation)
    end
  end
end

app/helpers/user_maintenance/application_helper.rb
module UserMaintenance
  module ApplicationHelper
  end
end

app/views/layouts/user_maintenance/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UserMaintenance</title>
  <%= stylesheet_link_tag    "user_maintenance/application", media: "all" %>
  <%= javascript_include_tag "user_maintenance/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/user_maintenance/users/_form.html.haml
- if can?(:create, @user) || can?(:update_profile, @user)
  = form.input :email
  = form.input :last_name
  = form.input :first_name
- if can? :create, @user
  = form.input :password, :as => :password
  = form.input :password_confirmation, :as => :password
- if can? :update_role, @user
  = form.input :role, :collection => UserMaintenance::User.valid_roles_map, :include_blank => false
- if can? :update_profile, @user
  = form.button :submit, 'Update Profile'
  = link_to 'Cancel', profile_path
- else
  = form.button :submit
  = link_to 'Cancel', cancel_url

app/views/user_maintenance/users/_password_form.html.haml
= form.input :password, :as => :password
= form.input :password_confirmation, :as => :password
= form.button :submit, 'Change password'
= link_to 'Cancel', cancel_url

app/views/user_maintenance/users/edit.html.haml
= simple_form_for @user, :url => (can? :update_profile, @user) ? profile_path : user_path(@user), :html => { :class => 'form' } do |form|
  = render 'form', :form => form, :cancel_url => (can? :update_profile, @user) ? profile_path : user_path(@user)

app/views/user_maintenance/users/edit_password.html.haml
= simple_form_for current_user, :url => update_password_profile_path, :html => { :class => 'form' } do |form|
  .form-group
    = form.input :current_password, :as => :password, :input_html => { :class => 'form-control' }
  = render :partial => 'password_form', :locals => { :form => form, :cancel_url => profile_path }

app/views/user_maintenance/users/index.html.haml
%h1 Listing users

%table{:class => 'table table-striped'}
  %thead
    %th Name
    %th Email
    %th Role
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to "#{user.last_name}, #{user.first_name}", user_path(user)
        %td= mail_to user.email
        %td
          - user.roles.each do |role|
            = role.to_s.humanize

%br

= link_to 'New User', new_user_path

app/views/user_maintenance/users/new.html.haml
%h1 New user

= simple_form_for @user, :url => users_path, :html => { :class => 'form' } do |form|
  = render 'form', :form => form, :cancel_url => users_path

= link_to 'Back', users_path

app/views/user_maintenance/users/resetting_password.html.haml
= simple_form_for @user, :url => reset_password_user_path(@user), :html => { :class => 'form' } do |form|
  = render :partial => 'password_form', :locals => { :form => form, :cancel_url => user_path(@user) }

app/views/user_maintenance/users/show.html.haml
%dl
  %dt First name:
  %dd
    = @user.first_name

%dl
  %dt Last name:
  %dd
    = @user.last_name
%dl
  %dt Email:
  %dd
    = mail_to @user.email

%dl
  %dt Role:
  %dd
    - @user.roles.each do |role|
      = role.to_s.humanize
      %br

- if can? :enable, @user
  = link_to("#{(@user.enabled? ? 'Disable' : 'Enable')}", enable_user_path(@user), :method => :put)
- if can? :update_profile, @user
  = link_to 'Edit', edit_profile_path
- elsif can? :update_role, @user
  = link_to 'Edit', edit_user_path(@user)
- if can? :reset_password, @user
  = link_to 'Reset password', reset_password_user_path(@user)
- elsif can? :edit_password, @user
  = link_to 'Change password', edit_password_profile_path
- if cannot? :update_profile, @user
  = link_to 'Back', users_path